name: todo
description: "A todo app project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_size_text: ^3.0.0
  day_night_time_picker: ^1.3.1
  flutter_animate: ^4.5.0
  iconly: ^1.0.1
  path_provider: ^2.1.3
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
